site_name: University Physics 201
site_url: https://lhs-beane.github.io/CollegePhysics201

theme:
  name: material

markdown_extensions:
  - admonition
  - footnotes
  - meta
  - def_list
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


nav:
  - Home: index.md
  - Week 1: week1/index.md
  - Week 2: week2/index.md
  - Week 3: week3/index.md
  - Week 4: week4/index.md
  - Week 5: week5/index.md
  - Week 6: week6/index.md
  - Week 7: week7/index.md
  - Week 8:
      - Overview: week8/index.md
      - Simple Harmonic Motion: week8/shm.md
      - Energy in Oscillations: week8/energy.md
      - Pendulums: week8/pendulums.md
      - Damping & Resonance: week8/damping.md
      - Problem Set: week8/problems.md


